import argparse

from model_features import predict_probability_from_runtime_file


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Run inference from a runtime_features.json window generated by the dashboard."
    )
    parser.add_argument("--input", required=True)
    parser.add_argument("--model", default="ai_model.joblib")
    args = parser.parse_args()

    probability = predict_probability_from_runtime_file(args.input, args.model)
    print(f"{probability:.4f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
