from __future__ import annotations

import argparse
import json

from model_features import build_prediction_payload


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Run inference from a runtime_features.json window generated by the dashboard."
    )
    parser.add_argument("--input", required=True)
    parser.add_argument("--model", default="ai_model.joblib")
    args = parser.parse_args()

    payload = build_prediction_payload(args.input, args.model)
    print(json.dumps(payload, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
